name: Lint

on:
  push:
    paths:
      - '*.py'

env:
  PYTHON_VERSION: 3.11
  POETRY_VERSION: 1.1.7

jobs:
  check-lint-and-styling:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.2
          architecture: x64
      - repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.2.0
      - name: set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

  check-type-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.2
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v1
      - name: Poetry Version
        run: |
          poetry --version
      - name: Poetry Install Dependencies
        run: |
          poetry install --no-interaction
      - name: Cache Poetry cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}
      - name: Install mypy
        run: pip install mypy
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run mypy
        run: poetry run mypy src
      - name: Run pytest
        run: poetry run pytest
